### PR TITLE
#103 Update sharp version

### PR DESCRIPTION
**Pull request by rptoma**
#103

### CODE REVIEW

**Comment by parostatkiem** [comment]
Hey @bigtiger could you have a look at this PR?
We'd like to use your wonderful avatars in [Kyma](https://kyma-project.io/ ) but we're unable to do so because it doesn't support the LTS Node 😞

**Review by bigtiger — APPROVED** [review]

**Comment by bigtiger** [comment]
LGTM but I don't have write access. @itsthatguy?

**Comment by parostatkiem** [comment]
Thank you @bigtiger for taking care!
Now, as far as I can see @rylnd also has the Power Of Merge - @rylnd could you use it, please?

**Comment by rylnd** [comment]
I'm sorry, I also do not have merge access. I've reached out to @itsthatguy to see if we can't sort this out.

**Review by itsthatguy — APPROVED** [review]

**Comment by gianlazz** [comment]
The npm module hasn't been updated with this change. How can I make use of this? I tried installing the repo directly however that doesn't seem to work either.

**Comment by rylnd** [comment]
@gianlazz I've just release `0.5.0`, which should include this change. Please give that a shot and let me know if you have further issues.

**Pull request merged**
